version: "3.7"

networks:
  network: 
    name: external2
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports: 
      - 8080:8080
    networks:
      network:
        ipv4_address: 10.5.0.5
  sidecar:
    build: keycloak/
    container_name: sidecar
    entrypoint: ["/usr/bin/bash", "-c", "/opt/docker/test.sh http://10.5.0.5:8080"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - keycloak
    networks:
      network:
        ipv4_address: 10.5.0.6
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 10.5.0.7
volumes:
  db:
    driver: local